/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import bbdd.ASNConexion;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sebas
 */
public class ASNMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ASNMenuPrincipal
     */
    public ASNMenuPrincipal() throws Exception {
        initComponents();
        String tipoUsuario = (String) (ASNLogin.ASNUsuarioLogado[2]);
        labelFecha.setText(java.time.LocalDate.now().toString());
        labelFacultativo.setText("Facultativo: " + (ASNLogin.ASNUsuarioLogado[0]));
        labelNumeroCol.setText("Nº de colegiado: " + (ASNLogin.ASNUsuarioLogado[1]));
        DefaultTableModel modelo = (DefaultTableModel) tablaPaciente.getModel();

        if (tipoUsuario.equals("MEDICO")) {
            botonConsultas.setEnabled(true);
            botonPacientes.setEnabled(true);
            labelAgenciaCitas.setText("AGENDA MÉDICA");
            ASNConexion.ASNrecuperaCitasMedicas(modelo);
        } else if (tipoUsuario.equals("ENFERMERIA")) {
            botonEnfermeria.setEnabled(true);
            labelAgenciaCitas.setText("AGENDA ENFERMERÍA");
            ASNConexion.ASNrecuperaCitasEnfermeria(modelo);
        } else if (tipoUsuario.equals("ADMIN")) {
            botonPersonalMedico.setEnabled(true);
        }
    

}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelFacultativo = new javax.swing.JLabel();
        labelNumeroCol = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonConsultas = new javax.swing.JButton();
        botonPacientes = new javax.swing.JButton();
        botonEnfermeria = new javax.swing.JButton();
        botonPersonalMedico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaciente = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        labelAgenciaCitas = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelFacultativo.setText("jLabel1");

        labelNumeroCol.setText("jLabel1");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\sebas\\Documents\\NetBeansProjects\\ASNConsultorio\\recursos\\logo_good.png")); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        botonConsultas.setBackground(new java.awt.Color(51, 153, 255));
        botonConsultas.setForeground(new java.awt.Color(255, 255, 255));
        botonConsultas.setText("CONSULTAS");
        botonConsultas.setEnabled(false);
        botonConsultas.setPreferredSize(new java.awt.Dimension(100, 100));
        botonConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConsultasActionPerformed(evt);
            }
        });

        botonPacientes.setBackground(new java.awt.Color(51, 153, 255));
        botonPacientes.setForeground(new java.awt.Color(255, 255, 255));
        botonPacientes.setText("PACIENTES");
        botonPacientes.setEnabled(false);
        botonPacientes.setPreferredSize(new java.awt.Dimension(100, 100));
        botonPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacientesActionPerformed(evt);
            }
        });

        botonEnfermeria.setBackground(new java.awt.Color(51, 153, 255));
        botonEnfermeria.setForeground(new java.awt.Color(255, 255, 255));
        botonEnfermeria.setText("ENFERMERÍA");
        botonEnfermeria.setEnabled(false);
        botonEnfermeria.setPreferredSize(new java.awt.Dimension(100, 100));
        botonEnfermeria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEnfermeriaActionPerformed(evt);
            }
        });

        botonPersonalMedico.setBackground(new java.awt.Color(51, 153, 255));
        botonPersonalMedico.setForeground(new java.awt.Color(255, 255, 255));
        botonPersonalMedico.setText("PRESONAL MÉDICO");
        botonPersonalMedico.setEnabled(false);
        botonPersonalMedico.setPreferredSize(new java.awt.Dimension(100, 100));
        botonPersonalMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPersonalMedicoActionPerformed(evt);
            }
        });

        tablaPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE", "DIA", "HORA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPaciente);

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\sebas\\Documents\\NetBeansProjects\\ASNConsultorio\\recursos\\principal.png")); // NOI18N

        labelAgenciaCitas.setForeground(new java.awt.Color(255, 255, 255));
        labelAgenciaCitas.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(botonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(botonEnfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(botonPersonalMedico, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAgenciaCitas))
                        .addGap(168, 168, 168)
                        .addComponent(jLabel5)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPacientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonEnfermeria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPersonalMedico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelAgenciaCitas)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89))))
        );

        labelFecha.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumeroCol)
                    .addComponent(labelFecha)
                    .addComponent(labelFacultativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelFecha)
                        .addGap(18, 18, 18)
                        .addComponent(labelFacultativo)
                        .addGap(18, 18, 18)
                        .addComponent(labelNumeroCol)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConsultasActionPerformed
        // TODO add your handling code here:
        ASNMedico m = new ASNMedico();
        m.setVisible(true);
    }//GEN-LAST:event_botonConsultasActionPerformed

    private void botonPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacientesActionPerformed
        // TODO add your handling code here:
        ASNPacientes p = new ASNPacientes(this,true);
        p.setVisible(true);
    }//GEN-LAST:event_botonPacientesActionPerformed

    private void botonEnfermeriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEnfermeriaActionPerformed
        // TODO add your handling code here:
        ASNEnfermeria e = new ASNEnfermeria();
        e.setVisible(true);
    }//GEN-LAST:event_botonEnfermeriaActionPerformed

    private void botonPersonalMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPersonalMedicoActionPerformed
        // TODO add your handling code here:
        ASNPersonalMedico pm = new ASNPersonalMedico(this,true);
        pm.setVisible(true);
    }//GEN-LAST:event_botonPersonalMedicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

}
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ASNMenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ASNMenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ASNMenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);

} catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ASNMenuPrincipal.class  

.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new ASNMenuPrincipal().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(ASNMenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultas;
    private javax.swing.JButton botonEnfermeria;
    private javax.swing.JButton botonPacientes;
    private javax.swing.JButton botonPersonalMedico;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAgenciaCitas;
    private javax.swing.JLabel labelFacultativo;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNumeroCol;
    private javax.swing.JTable tablaPaciente;
    // End of variables declaration//GEN-END:variables
}



